// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlAUqNzjqhliLDJulrcotLIP1J5IPTBew',
    appId: '1:103498613498:web:0f05dd9187c0d12c5f3f43',
    messagingSenderId: '103498613498',
    projectId: 'missingpeople-367f5',
    authDomain: 'missingpeople-367f5.firebaseapp.com',
    storageBucket: 'missingpeople-367f5.appspot.com',
    measurementId: 'G-K4FJVT4KTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrsfSOTBADkbYOUTv7v8uyYBDH8-LXXA',
    appId: '1:103498613498:android:284ea1d8875698005f3f43',
    messagingSenderId: '103498613498',
    projectId: 'missingpeople-367f5',
    storageBucket: 'missingpeople-367f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ4tXyiUHaPbXMNUJ6AqfEgTKeUA2IyQ4',
    appId: '1:103498613498:ios:b039b6139a213b035f3f43',
    messagingSenderId: '103498613498',
    projectId: 'missingpeople-367f5',
    storageBucket: 'missingpeople-367f5.appspot.com',
    iosClientId: '103498613498-fibcd1si2oe16efsrh8cma011uk0rk7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.missingpeple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ4tXyiUHaPbXMNUJ6AqfEgTKeUA2IyQ4',
    appId: '1:103498613498:ios:b039b6139a213b035f3f43',
    messagingSenderId: '103498613498',
    projectId: 'missingpeople-367f5',
    storageBucket: 'missingpeople-367f5.appspot.com',
    iosClientId: '103498613498-fibcd1si2oe16efsrh8cma011uk0rk7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.missingpeple',
  );
}
